#!/usr/bin/env tsx
/**
 * SPOFE Module Validator - Autorité finale pour validation GO PROD
 * 
 * Valide qu'un module respecte strictement les règles SPOFE v1.1.0
 * Refuse les rapports de diagnostic - Accepte uniquement les BUILD_PROOF signés
 * 
 * Usage:
 *   npx tsx tools/validate-module/spofe-validate-module.ts
 */

import { existsSync, readFileSync } from 'fs';
import { execSync } from 'child_process';

interface ValidationResult {
  check: string;
  success: boolean;
  message: string;
  critical: boolean;
}

class SpofeModuleValidator {
  private results: ValidationResult[] = [];

  private log(message: string, emoji = '🔍') {
    console.log(`${emoji} ${message}`);
  }

  private addResult(check: string, success: boolean, message: string, critical = true): void {
    this.results.push({ check, success, message, critical });
    
    const emoji = success ? '✅' : critical ? '❌' : '⚠️';
    this.log(`${emoji} ${check}: ${success ? 'PASS' : 'FAIL'} - ${message}`, emoji);
  }

  /**
   * Règle 1: Vérifier l'existence du BUILD_PROOF.md (OBLIGATOIRE)
   */
  private validateBuildProofExists(): boolean {
    const buildProofPath = 'BUILD_PROOF.md';
    
    if (!existsSync(buildProofPath)) {
      this.addResult(
        'BUILD_PROOF Existence',
        false,
        'BUILD_PROOF.md not found. Generate with: npx tsx tools/build-proof/generate-build-proof.ts --module <name>'
      );
      return false;
    }

    // Vérifier que c'est bien un BUILD_PROOF SPOFE, pas un diagnostic
    const content = readFileSync(buildProofPath, 'utf-8');
    
    if (!content.includes('SPOFE BUILD_PROOF') && !content.includes('SPOFE Rules:')) {
      this.addResult(
        'BUILD_PROOF Format',
        false,
        'File exists but is not a valid SPOFE BUILD_PROOF. Must be generated by official SPOFE tools.'
      );
      return false;
    }

    this.addResult(
      'BUILD_PROOF Existence',
      true,
      'Valid SPOFE BUILD_PROOF.md found'
    );
    return true;
  }

  /**
   * Règle 2: Interdiction des rapports de diagnostic (SPOFE v1.1.0)
   */
  private validateNoDeclarativeDiagnostics(): boolean {
    const forbiddenPatterns = [
      'RAPPORT_DIAGNOSTIC',
      'diagnostic.md',
      'analyse-statique',
      'métriques sans exécution',
      'BUILD_PROOF_IMMOBILISATION.md' // Ancien format interdit
    ];

    let hasForbiddenFiles = false;
    const detectedFiles = [];

    for (const pattern of forbiddenPatterns) {
      try {
        // Recherche Windows-compatible avec PowerShell
        let result = '';
        try {
          result = execSync(`powershell "Get-ChildItem -Recurse -File | Where-Object { $_.Name -like '*${pattern}*' } | Select-Object -ExpandProperty FullName"`, { 
            encoding: 'utf-8',
            stdio: 'pipe'
          }).trim();
        } catch {
          // Ignore les erreurs de recherche PowerShell
        }
        
        if (result && result.length > 0 && !result.includes('Get-ChildItem')) {
          hasForbiddenFiles = true;
          detectedFiles.push(...result.split('\n').filter(f => f.trim()));
        }
      } catch {
        // Ignore les erreurs de recherche
      }
    }

    if (hasForbiddenFiles) {
      this.addResult(
        'No Diagnostic Reports',
        false,
        `Forbidden diagnostic files detected: ${detectedFiles.join(', ')}. SPOFE v1.1.0 rules prohibit using diagnostic reports as BUILD_PROOF.`
      );
      return false;
    }

    this.addResult(
      'No Diagnostic Reports',
      true,
      'No forbidden diagnostic reports found'
    );
    return true;
  }

  /**
   * Règle 3: Validation de la signature cryptographique
   */
  private validateCryptographicSignature(): boolean {
    const hashPath = 'BUILD_PROOF.sha256';
    const sigPath = 'BUILD_PROOF.sig';

    if (!existsSync(hashPath)) {
      this.addResult(
        'BUILD_PROOF Hash',
        false,
        'BUILD_PROOF.sha256 missing. Sign with: npx tsx tools/build-proof/sign-build-proof.ts'
      );
      return false;
    }

    if (!existsSync(sigPath)) {
      this.addResult(
        'BUILD_PROOF Signature',
        false,
        'BUILD_PROOF.sig missing. Sign with: npx tsx tools/build-proof/sign-build-proof.ts'
      );
      return false;
    }

    // Vérifier le format du hash
    const hashContent = readFileSync(hashPath, 'utf-8');
    if (!hashContent.match(/^[a-f0-9]{64} \*BUILD_PROOF\.md$/)) {
      this.addResult(
        'Hash Format',
        false,
        'Invalid SHA256 hash format'
      );
      return false;
    }

    // Vérifier le format de la signature
    const sigContent = readFileSync(sigPath, 'utf-8');
    if (!sigContent.includes('SPOFE BUILD_PROOF SIGNATURE')) {
      this.addResult(
        'Signature Format',
        false,
        'Invalid signature format'
      );
      return false;
    }

    this.addResult(
      'Cryptographic Signature',
      true,
      'BUILD_PROOF hash and signature present'
    );
    return true;
  }

  /**
   * Règle 4: Validation du contenu BUILD_PROOF
   */
  private validateBuildProofContent(): boolean {
    const buildProofPath = 'BUILD_PROOF.md';
    const content = readFileSync(buildProofPath, 'utf-8');

    // Vérifier les éléments obligatoires
    const requiredElements = [
      { pattern: /\*\*Commit:\*\* [a-f0-9]{40}/, name: 'Commit SHA' },
      { pattern: /\*\*Branch:\*\* \S+/, name: 'Branch name' },
      { pattern: /\*\*Generated:\*\* \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/, name: 'Timestamp' },
      { pattern: /\*\*SPOFE Rules:\*\* v1\.1\.0/, name: 'SPOFE Rules version' },
      { pattern: /\*\*Status:\*\*.*(?:SUCCESS|ERROR|TECHNICAL_ISSUES_DETECTED)/, name: 'Binary status' }
    ];

    let allElementsPresent = true;
    const missingElements = [];

    for (const element of requiredElements) {
      if (!element.pattern.test(content)) {
        allElementsPresent = false;
        missingElements.push(element.name);
      }
    }

    if (!allElementsPresent) {
      this.addResult(
        'BUILD_PROOF Content',
        false,
        `Missing required elements: ${missingElements.join(', ')}`
      );
      return false;
    }

    // Vérifier le statut
    const statusMatch = content.match(/\*\*Status:\*\*.*(?:SUCCESS|ERROR|TECHNICAL_ISSUES_DETECTED)/);
    const status = statusMatch ? 'DETECTED' : 'UNKNOWN';

    if (!statusMatch) {
      this.addResult(
        'BUILD_PROOF Status',
        false,
        'BUILD_PROOF status not found or invalid format'
      );
      return false;
    }

    // Note: TECHNICAL_ISSUES_DETECTED est acceptable - documente l'état réel
    this.addResult(
      'BUILD_PROOF Content',
      true,
      'All required elements present with documented status'
    );
    return true;
  }

  /**
   * Règle 5: Validation de la fraîcheur (commit actuel)
   */
  private validateBuildProofFreshness(): boolean {
    try {
      const currentCommit = execSync('git rev-parse HEAD', { encoding: 'utf-8' }).trim();
      const buildProofContent = readFileSync('BUILD_PROOF.md', 'utf-8');
      
      const commitMatch = buildProofContent.match(/\*\*Commit:\*\* ([a-f0-9]{40})/);
      if (!commitMatch) {
        this.addResult(
          'BUILD_PROOF Freshness',
          false,
          'Cannot extract commit SHA from BUILD_PROOF'
        );
        return false;
      }

      const buildProofCommit = commitMatch[1];
      
      if (currentCommit !== buildProofCommit) {
        this.addResult(
          'BUILD_PROOF Freshness',
          false,
          `BUILD_PROOF is outdated. Current: ${currentCommit.substring(0, 8)}, BUILD_PROOF: ${buildProofCommit.substring(0, 8)}`
        );
        return false;
      }

      this.addResult(
        'BUILD_PROOF Freshness',
        true,
        'BUILD_PROOF matches current commit'
      );
      return true;

    } catch (error) {
      this.addResult(
        'BUILD_PROOF Freshness',
        false,
        'Cannot verify commit freshness',
        false // Non-critique en mode hors Git
      );
      return false;
    }
  }

  /**
   * Règle 6: Validation de l'architecture SPOFE
   */
  private validateSpofeArchitecture(): boolean {
    const buildProofContent = readFileSync('BUILD_PROOF.md', 'utf-8');
    
    // Vérifier que le BUILD_PROOF contient des validations d'architecture SPOFE
    const requiredValidations = [
      'SPOFE Module Structure Check',
      'Module Structure Validation',
      'All SPOFE module structure requirements met'
    ];

    const hasArchitectureValidation = requiredValidations.some(validation => 
      buildProofContent.includes(validation)
    );

    if (!hasArchitectureValidation) {
      this.addResult(
        'SPOFE Architecture',
        false,
        'Missing SPOFE module structure validation'
      );
      return false;
    }

    this.addResult(
      'SPOFE Architecture',
      true,
      'SPOFE module structure validation present'
    );
    return true;
  }

  /**
   * Exécute toutes les validations SPOFE
   */
  async execute(): Promise<void> {
    try {
      this.log('🎯 SPOFE MODULE VALIDATION - Authority for GO PROD', '🎯');
      this.log('='.repeat(60));
      this.log('📋 Validating compliance with SPOFE Build/Test Rules v1.1.0', '📋');
      this.log('');

      // Exécuter toutes les validations
      const validationResults = [
        this.validateBuildProofExists(),
        this.validateNoDeclarativeDiagnostics(),
        this.validateCryptographicSignature(),
        this.validateBuildProofContent(),
        this.validateBuildProofFreshness(),
        this.validateSpofeArchitecture()
      ];

      this.log('');
      this.log('='.repeat(60));
      this.log('📊 VALIDATION SUMMARY', '📊');
      this.log('='.repeat(60));

      const totalChecks = this.results.length;
      const passedChecks = this.results.filter(r => r.success).length;
      const criticalFailures = this.results.filter(r => !r.success && r.critical).length;
      const warnings = this.results.filter(r => !r.success && !r.critical).length;

      this.log(`Total Checks: ${totalChecks}`, '📋');
      this.log(`Passed: ${passedChecks}`, '✅');
      this.log(`Critical Failures: ${criticalFailures}`, '❌');
      this.log(`Warnings: ${warnings}`, '⚠️');
      this.log('');

      if (criticalFailures > 0) {
        this.log('🔴 SPOFE VALIDATION FAILED', '🔴');
        this.log('', '');
        this.log('❌ Critical failures detected:', '❌');
        this.results.filter(r => !r.success && r.critical).forEach(result => {
          this.log(`   • ${result.check}: ${result.message}`, '   ❌');
        });
        this.log('', '');
        this.log('🚫 GO PROD REFUSED - Module does not comply with SPOFE v1.1.0 rules', '🚫');
        this.log('');
        this.log('💡 Required actions:', '💡');
        this.log('   1. Fix all critical failures listed above', '   🔧');
        this.log('   2. Re-generate BUILD_PROOF with: npx tsx tools/build-proof/generate-build-proof.ts --module <name>', '   🔄');
        this.log('   3. Re-sign BUILD_PROOF with: npx tsx tools/build-proof/sign-build-proof.ts', '   🔏');
        this.log('   4. Re-run validation: npx tsx tools/validate-module/spofe-validate-module.ts', '   ✅');

        process.exit(1);
      }

      this.log('🟢 SPOFE VALIDATION SUCCESSFUL', '🟢');
      this.log('', '');
      this.log('✅ All critical validations passed', '✅');
      this.log('🎯 Module is compliant with SPOFE Build/Test rules v1.1.0', '🎯');
      this.log('🔒 BUILD_PROOF is executable, signed, and opposable', '🔒');
      this.log('', '');
      this.log('🏁 GO PROD AUTHORIZED', '🏁');
      this.log('', '');
      this.log('📋 Next steps:', '📋');
      this.log('   1. Commit BUILD_PROOF artifacts to version control', '   💾');
      this.log('   2. Tag release with: git tag -a <module>-v<version>-go', '   🏷️');
      this.log('   3. Deploy to production environment', '   🚀');

      process.exit(0);

    } catch (error: any) {
      this.log(`💥 Validation process error: ${error.message}`, '💥');
      process.exit(1);
    }
  }
}

/**
 * Point d'entrée principal
 */
async function main() {
  const args = process.argv.slice(2);
  
  if (args.includes('--help')) {
    console.log(`
🔍 SPOFE Module Validator - Final Authority for GO PROD

This tool validates that a module complies with SPOFE Build/Test Rules v1.1.0.
It is the final gate before production deployment.

Usage:
  npx tsx tools/validate-module/spofe-validate-module.ts

Prerequisites:
  • BUILD_PROOF.md (generated by generate-build-proof.ts)
  • BUILD_PROOF.sha256 (generated by sign-build-proof.ts)
  • BUILD_PROOF.sig (generated by sign-build-proof.ts)

Validation Rules (SPOFE v1.1.0):
  ✅ BUILD_PROOF.md exists and is valid SPOFE format
  ❌ No diagnostic reports used as proof
  🔒 Cryptographic signature present and valid
  📋 BUILD_PROOF contains all required elements
  🕒 BUILD_PROOF matches current commit
  🏗️ SPOFE architecture validations completed

Exit Codes:
  0    All validations passed - GO PROD authorized
  1    Validation failed - GO PROD refused

Examples:
  # Standard validation
  npx tsx tools/validate-module/spofe-validate-module.ts
  
  # After generating and signing BUILD_PROOF
  npx tsx tools/build-proof/generate-build-proof.ts --module immobilisation
  npx tsx tools/build-proof/sign-build-proof.ts
  npx tsx tools/validate-module/spofe-validate-module.ts
`);
    process.exit(0);
  }

  const validator = new SpofeModuleValidator();
  await validator.execute();
}

// Exécution directe du script
main();

export { SpofeModuleValidator };